#!/usr/bin/env Rscript

###Chutes and Ladders Code modified from https://kateto.net/network-visualization
#install.packages("network") 
#install.packages("sna")
#install.packages("ggraph")
#install.packages("visNetwork")
#install.packages("threejs")
#install.packages("networkD3")
#install.packages("ndtv")
library("network") 
library("sna")
library("ggraph")
library("visNetwork")
library("threejs")
library("networkD3")
library("ndtv")
library("igraph")

###Read in data, create network#####
C_L_nodes <- read.csv("C_L_nodes_mod.csv", header=TRUE, as.is=TRUE)
C_L_edges <- read.csv("C_L_edges_mod.csv", header=TRUE, as.is=TRUE)

net <- graph_from_data_frame(d=C_L_edges, vertices=C_L_nodes, directed=TRUE) 
netup <- graph_from_data_frame(d=C_L_edges, vertices=C_L_nodes, directed=TRUE)
V(netup)$frame.color <- NA 

##### Give it coordinates -- this is weird #######
tkid = tkplot(net,canvas.width = 350, canvas.height = 350)
transLat <- C_L_nodes$latitude
transLon <- 10-C_L_nodes$longitude
coords <- cbind(transLon,transLat)
tkplot.setcoords(tkid, coords)
l <- tkplot.getcoords(tkid) # grab the coordinates from tkplot
####Generate the shortest path####
play <- shortest_paths(net, from = V(net)["0"], to = V(net)["100"], output = "both")
length(play)
####Generate histogram of random walks####
plays = 0
for(i in 1:10000)
{
  playR <- random_walk(net, V(net)["0"], 100, mode = "out")
  plays <- c(plays, length(playR))
}
mean(plays)
plot(hist(plays), main = "Probability of Winning at Certain Number of Turns")
####Generate play through the the network####
playR <- random_walk(net, V(net)["0"], 100, mode = "out")
# Get the edge id from the nodelist generated by the path:
playRR <- as_ids(playR)
nodelist <-c(playRR[1])
for(i in 2:(length(playRR)-1)) {
nodelist <- append(nodelist,playRR[i])
nodelist <- append(nodelist,playRR[i])
}
nodelist <- append(nodelist,playRR[length(playRR)])
epath <- get.edge.ids(net, nodelist)

# Generate edge color variable to plot the path:
ecol <- rep("grey80", ecount(net))
ecol[unlist(epath)] <- "orange"
ecolup <- rep(rgb(0, 0, 0, 0, maxColorValue=255), ecount(netup))
ecolup[unlist(epath)] <- "orange"
# Generate edge width variable to plot the path:
ew <- rep(1, ecount(net))
ew[unlist(epath)] <- 4

# Generate node color variable to plot the path:
vcol <- rep("gray40", vcount(net))
vcol[unlist(playR)] <- "gold"
vcolup <- rep(rgb(0, 0, 0, 0, maxColorValue=255), vcount(netup))

plot(net, vertex.color=vcol, edge.color=ecol, edge.width=ew, edge.arrow.mode=2, rescale = F, 
     vertex.label.color="white", layout=l*-.2+1.0,canvas.width = 350, canvas.height = 350)
par(new=TRUE)
plot(netup, vertex.color=vcolup, edge.color=ecolup, edge.width=ew, edge.arrow.mode=2, rescale = F, 
     vertex.label.color=rgb(0, 0, 0, 0, maxColorValue=255), layout=l*-.2+1.0,canvas.width = 350, canvas.height = 350)